name: CI
on: [push, pull_request]
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        gemfile:
          - Gemfile
          - gemfiles/rails_7_0_propshaft.gemfile
          - gemfiles/rails_7_1_propshaft.gemfile
          - gemfiles/rails_7_0_sprockets.gemfile
          - gemfiles/rails_7_1_sprockets.gemfile
        continue-on-error: [ false ]

    name: ${{ format('Tests (Ruby {0}, {1})', matrix.ruby-version, matrix.gemfile) }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.continue-on-error }}

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v3

      - name: Remove Gemfile lock
        run: |
          rm $BUNDLE_GEMFILE.lock

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rake
